create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer null,
    num_red_ml integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    sku text not null,
    r integer null,
    g integer null,
    b integer null,
    d integer null,
    quantity integer null,
    name text null,
    price integer null,
    constraint potion_inventory2_pkey1 primary key (sku)
  ) tablespace pg_default;

create table
  public.carts (
    id bigint generated by default as identity,
    name text null,
    class text null,
    level integer null,
    constraint carts2_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer not null,
    item_sku text not null,
    quantity integer null,
    constraint cart_items_pkey primary key (cart_id, item_sku),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint public_cart_items_item_sku_fkey foreign key (item_sku) references potion_inventory (sku)
  ) tablespace pg_default;